### ISSUE TITLE
Chapter 3.10.1 - connection_string_without_db()

### ISSUE THREAD

**Issue by Dlozanof** [LukeMathWalker/zero-to-production#174] opened 2022-12-08 19:35 UTC
In the indicated chapter it is proposed to use the function `connection_string_without_db()` to connect to the Postgress instance, but not to a specific database. This does not seem to be aligned with Postgress expectations, since if the database is not indicated it is defaulted to the value of the user. Example for user `user`:

```
thread 'register_offer_returns_400_for_invalid_data' panicked at 'Failed to connect to Postgress: Database(PgDatabaseError { severity: Fatal, code: "3D000", message: "database \"testst\" does not exist", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("postinit.c"), line: Some(941), routine: Some("InitPostgres") })', tests/healthj_check.rs:111:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am no expert in backend/dbs at all, so I checked on the internet and there seems to be a known behavior:
- https://stackoverflow.com/questions/4483139/how-do-i-connect-to-postgresql-without-specifying-a-database-name
- https://stackoverflow.com/questions/51015561/how-to-connect-to-postgresql-db-without-a-database-name-from-aws-rds

Both recommend using `postgres` database, which I tried and works as expected.

**Comment by andioz** [comment] 2022-12-23 10:33
Exactly the same here. Using `postgres` as db-name seems to work. I wonder if there changed something recently inside the `sqlx` package of in PostgrSQL itself recently? Because I think the code in the book (and in the example code here in the repo) worked at the time of writing. Any idea?

**Comment by LukeMathWalker** [comment] 2022-12-23 10:38
This definitely worked - I'll have to do some digging.

**Comment by LukeMathWalker** [comment] 2023-02-19 18:47
I can't seem to be able to reproduce the problem 🤔

**Comment by fmsrodrigues** [comment] 2023-06-15 20:24
Had this error today. Adding "/postgres" to the end of the format string solved the problem even with a user not being named "postgres", in my case the user was "docker"

```
pub fn connection_string_without_db(&self) -> String {
    format!(
        "postgres://{}:{}@{}:{}/postgres",
        self.username, self.password, self.host, self.port
    )
}
```

ty @Dlozanof

**Comment by fmsrodrigues** [comment] 2023-06-21 21:05
At chapter 5.4 when we change the `connection_string_without_db` function, we need to add an call to `.database("postgres")` to the end of the `without_db` function to avoid having the same problem as before.

I don't know if this is the best approaching to have a default value that gets overwritten by another function in the builder pattern, but it's the change that I knew that could work.

```
impl DatabaseSettings {
    pub fn with_db(&self) -> PgConnectOptions {
        self.without_db().database(&self.database_name)
    }

    pub fn without_db(&self) -> PgConnectOptions {
        PgConnectOptions::new()
            .host(&self.host)
            .username(&self.username)
            .password(&self.password.expose_secret())
            .port(self.port)
            .database("postgres")
    }
}
```

**Comment by ishtms** [comment] 2023-07-20 17:51
@fmsrodrigues  Instead of
 ```rs
 pub fn connection_string_without_db(&self) -> String {
     format!(
         "postgres://{}:{}@{}:{}/postgres",
         self.username, self.password, self.host, self.port
     )
 }
```
You need to return this instead
```rs
format!("postgres://{}:{}@{}:{}", self.username, self.password, self.host, self.port)
```
We handle appending a unique generated database name inside `spawn_app()`
```rs
let mut configuration = get_configuration().expect("Failed to read configuration.");
configuration.database.database_name = Uuid::new_v4().to_string();
```

And inside the `configure_database()` we're using a randomly generated database that was set above, in the `spawn_app()` function.
```rs
 connection
    .execute(format!(r#"CREATE DATABASE "{}";"#, config.database_name).as_str()) .await
    .expect("Failed to create database.");
```

**Comment by ishtms** [comment] 2023-07-20 17:52
Also we're creating that database with unique indentifer by running a db migration inside `configure_database()`

```
    connection
        .execute(&*format!(r#"CREATE DATABASE {};"#, config.database_name))
        .await
        .expect("Failed to create database.");
```

**Comment by crazyoptimist** [comment] 2024-04-10 21:07
I had the same problem today.

For postgres, I don't use `postgres` as username, I use `justuser` instead. And connection to the database without database name failed with an error like "Database `justuser` doesn't exist".

Then I experimented this:
- Remove the database name from .env file
- Run `sqlx database create`
- Now you will see a new database has been created with the name `justuser`
- Run `cargo test` -> Everything is green

So, this is probably the Postgres that expects a database with the same name as username or I'm not exactly sure and don't have much time to dig into the Postgres doc to see what actually happens.

If you use `postgres` as username, a database named `postgres` exists by default (for maintenance purpose I guess?). That's why you couldn't reproduce this issue, @LukeMathWalker 

This issue should be clearly addressed in the future release of the book.

**Comment by LukeMathWalker** [comment] 2024-04-11 08:26
I see, thanks for the investigation @crazyoptimist!

**Comment by LukeMathWalker** [comment] 2024-09-01 12:10
Solved in the next book release. Thanks everyone!

**Closed by LukeMathWalker** 2024-09-01 12:10 UTC
