### ISSUE TITLE
Chapter 1.4: Git hooks c.f. CI/CD pipelines

### ISSUE THREAD

**Issue by bbros-dev** [LukeMathWalker/zero-to-production#56] opened 2021-03-02 09:29 UTC
Thank you for taking the time and making the effort to write this book.

I was a little surprised to find no mention of Git hooks c.f. CI/CD services for fast feedback activities like formatting and linting - usually run via a pre-commit hook. 
This definitely smooths the review process, and stops the CI/CD from breaking for trivia that should not make its way into a commit - IMO.

The use of [left-hook (go binary)](https://github.com/Arkweid/lefthook), husky or pre-commit ensure the hook configuration and scripts reside in the project.

I wonder if longer compile times could make git hooks appear to be as fast/slow as external CI/CD services?
Any other reasons to stay clear of git hooks?

**Comment by bbros-dev** [comment] 2021-03-02 10:03
In case this is of interest, using lefthook, crate checking is likely best done pre-push:

```yaml
# lefthook.yml
pre-push:
  commands:
    cargo-audit:
      tags: backend security
      run: cargo audit
    cargo-deny:
      tags: backend security
      run: cargo deny check
pre-commit:
  parallel: false
  commands:
    cargo-format:
    tags: backend style
    run: cargo fmt -- --backup --check --files-with-diff
```

**Comment by LukeMathWalker** [comment] 2021-03-06 15:28
I used to be a fan of git pre-push hooks, but I have honestly grown less and less fond of them over time: there is no way to ensure all developers working on a project have them installed (or update them if they change over time).

In particular, I do not buy into the philosophy of "only correct code should be committed": when using short-lived branch it is fairly useful to commit "broken" code which can then be discussed with other teammates. The commit can later be squashed when merging or prettified according to whatever philosophy the dev team prefers. 

Said that, a pre-push hook for formatting is quite convenient: I'll add a footnote about it in the next release. Thanks for bringing it up 😁

**Closed by LukeMathWalker** 2021-03-06 15:28 UTC

**Comment by bbros-dev** [comment] 2021-03-07 02:51
> ... there is no way to ensure all developers working on a project have them installed (or update them if they change over time).

Hmm, "no way" might be a bit strong - it is done by having the hooks and any utility scripts in the code repository - see the lefthook link I provided. Developers are always using the same hooks when they are at the same commit id.

I believe you are correct, in saying there is "no Rust-native way" to do this but we aren't averse to having a go binary requirement "for trivia that should not make its way into a commit" - we don't classify spikes, RFC's or PoC all of which might not be "working" as trivia.

> I do not buy into the philosophy of "only correct code should be committed"

A straw-man I believe.

I did mention speeding up the feedback cycle a couple of times and that has a real impact on how willing devs are to kick-off the feedback loop. On non-trivial sized projects we do find considerable speed-ups by only checking changed files.

Overall I haven't yet found git-hooks cause a slow down on this Rust project - one of the points of undertaking this work so it'll be interesting to see how that plays out - not averse to revising our practices or flows, we just wanted to get an rough understanding of if so and by how much.

**Comment by LukeMathWalker** [comment] 2021-03-07 08:08
> Hmm, "no way" might be a bit strong - it is done by having the hooks and any utility scripts in the code repository - see the lefthook link I provided. Developers are always using the same hooks when they are at the same commit id.
> 
> I believe you are correct, in saying there is "no Rust-native way" to do this but we aren't averse to having a go binary requirement "for trivia that should not make its way into a commit" - we don't classify spikes, RFC's or PoC all of which might not be "working" as trivia.

You can make it convenient by having all the scripts and hooks there, but you can't enforce it - hooks are not automatically installed when the repository is cloned (by design).  
If something **must** be checked, it needs to happen in CI.  
git hooks are a convenience that developers on a project can opt-in (or opt-out) to use.

> > I do not buy into the philosophy of "only correct code should be committed"
> 
> A straw-man I believe.
> 
> I did mention speeding up the feedback cycle a couple of times and that has a real impact on how willing devs are to kick-off the feedback loop. On non-trivial sized projects we do find considerable speed-ups by only checking changed files.
> 
> Overall I haven't yet found git-hooks cause a slow down on this Rust project - one of the points of undertaking this work so it'll be interesting to see how that plays out - not averse to revising our practices or flows, we just wanted to get an rough understanding of if so and by how much.

You won't find me arguing against quick feedback loops, all the opposite!  
But git hooks are quick feedback loops with a side-effect - you can't push (or commit) if they fail.  
You can get a similar effect without being as opinionated using something like `cargo watch -x check -x test` - it'll be introduced later in the book. It's not as configurable as what you described so far (only run unit tests from files that changed), but you can also use `cargo watch` to run custom scripts - so I'm sure you could hook it up if you wanted to.
